---
- name: "EC2 start instance gitlab-runner"
  amazon.aws.ec2_instance:
    name:            "gitlab-runner"
    region:          "{{ vpc.region }}"
    vpc_subnet_id:   "{{ gitlab_runner_private_address_only | ternary(subnet_private.id, subnet_public.id) }}"
    key_name:        "gitlab-runner"
    network:
      assign_public_ip: "{{ not gitlab_runner_private_address_only }}"
    security_groups:
      - "gitlab-runner"
      - "{{ vpc.name }}-ssh"
      - "{{ vpc.name }}-icmp"
      - "{{ gitlab_runner_private_address_only | ternary('', 'public-ssh') }}"
    volumes:
      - device_name: /dev/sda1
        ebs:
          volume_type: gp3
          volume_size: "{{ gitlab_runner_ec2_volume_size_GB }}"
          delete_on_termination: true
    # 099720109477/ubuntu/images/hvm:ebs-ssd/ubuntu-focal-20.04-amd64-server-20220308
    image_id:        "ami-01896de1f162f0ab7"
    instance_role:   "gitlab-build-autoscale-runner"
    instance_type:   "t3.micro"
    state:           running
    purge_tags:      true
    wait:            true
  register:          ec2_instance_info

- name: "EC2 print instance gitlab-runner IP addresses"
  ansible.builtin.debug:
    msg:
      - "public IP:  {{ ec2_instance_info.instances[0].public_ip_address }}"
      - "private IP: {{ ec2_instance_info.instances[0].private_ip_address }}"

- name: "EC2 connect instance gitlab-runner from instance info"
  ansible.builtin.wait_for:
    host: "{{ gitlab_runner_private_address_only | ternary(ec2_instance_info.instances[0].private_ip_address, ec2_instance_info.instances[0].public_ip_address) }}"
    port: 22
    timeout: 60
  delegate_to: localhost
