# AWS playbook to create an EC2 instance that will host a gitlab runner
---
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Verify VPC identifiers are defined
      ansible.builtin.assert:
        that:
          - vpc.id != ""
          - vpc.inet_gateway_id != ""
          - subnet_public.id != ""
          - subnet_private.id != ""

- hosts: localhost
  connection: local
  gather_facts: false
  environment:
    # Ansible AWS modules
    AWS_ACCESS_KEY: "{{ aws_access_key }}"
    AWS_SECRET_KEY: "{{ aws_secret_key }}"
    AWS_EC2_REGION: "us-east-1"

    # AWS CLI
    AWS_ACCESS_KEY_ID:     "{{ aws_access_key }}"
    AWS_SECRET_ACCESS_KEY: "{{ aws_secret_key }}"
    AWS_DEFAULT_REGION:    "us-east-1"

  roles:
    - name: aws-vpc-gitlab
      role: aws-vpc-gitlab
