---
intranet:
  cidr: "10.0.0.0/8"

vpc:
  name:              "gitlab"
  cidr:              "10.0.0.0/16"
  region:            us-east-1
  zone:              a
  tags:
    app:             "gitlab"
  # the following can be user-specified, or if empty, populated at runtime
  # by the vpc playbook. They must be specified for other playbooks.
  id:                ""
  inet_gateway_id:   ""

subnet_public:
  name:              "gitlab-public"
  cidr:              "10.0.1.0/24"
  # the following can be user-specified, or if empty, populated at runtime
  # by the vpc playbook. They must be specified for other playbooks.
  id:                ""
  nat_gateway_id:    ""
  route_table_id:    ""

subnet_private:
  name:              "gitlab-private"
  cidr:              "10.0.2.0/24"
  # the following can be user-specified, or if empty, populated at runtime
  # by the vpc playbook. They must be specified for other playbooks.
  id:                ""
  route_table_id:    ""
