---
- name: Install python3-pip
  ansible.builtin.apt:
    pkg:
      - virtualenv
      - python3-setuptools
      - python3-pip
    state: latest
  become: true

- name: Upgrade pip
  ansible.builtin.pip:
    name: pip
    state: latest
  become: true
