- name: "Create VPC endpoint to S3"
  amazon.aws.ec2_vpc_endpoint:
    region:  "{{ vpc.region }}"
    vpc_id:  "{{ vpc.id }}"
    service: "com.amazonaws.{{ vpc.region }}.s3"
    # wait may result in Ansible querying an endpoint ID too fast for a
    # newly created endpoint to respond, returning an error.
    # As long as this step is far upstream of any dependencies,
    # it should be safe to continue without verification.
    wait:    true
    route_table_ids:
      - "{{ subnet_public.route_table_id }}"
      - "{{ subnet_private.route_table_id }}"
  register: result

- name: "Tag VPC endpoint to S3"
  amazon.aws.ec2_tag:
    region:       "{{ vpc.region }}"
    resource:     "{{ result.result.vpc_endpoint_id }}"
    tags:         "{{ vpc.tags | combine({'Name':vpc.name + '-s3'}) }}"
