---
- name: "Create {{ vpc.name }} VPC"
  amazon.aws.ec2_vpc_net:
    name:          "{{ vpc.name }}"
    cidr_block:    "{{ vpc.cidr }}"
    region:        "{{ vpc.region }}"
    dns_hostnames: true
    dns_support:   true
    tags:          "{{ vpc.tags }}"
  register: result

- name: "Set fact vpc.id"
  ansible.builtin.set_fact:
    vpc: "{{ vpc | combine({'id': result.vpc.id}) }}"
  when: vpc.id == ""

- name: "Create {{ vpc.name }} internet gateway"
  amazon.aws.ec2_vpc_igw:
    vpc_id:        "{{ vpc.id }}"
    region:        "{{ vpc.region }}"
    state:         "present"
    tags:          "{{ vpc.tags | combine({'Name':vpc.name}) }}"
  register: result

- name: "Set fact vpc.inet_gateway_id"
  ansible.builtin.set_fact:
    vpc: "{{ vpc | combine({'inet_gateway_id': result.gateway_id}) }}"
  when: vpc.inet_gateway_id == ""
