concurrent = 4
check_interval = 3
listen_address = ":{{ gitlab_metrics_server_port }}"
log_level = "info"

[session_server]
  listen_address = ":{{ gitlab_session_server_port }}"
  advertise_address = "{{ ansible_host }}:{{ gitlab_session_server_port }}"
  session_timeout = 1800
